Exp - 8 code review
virtual-labs/exp-d-flip-flop-verilog-iiith pull request #7
Opened 2022-04-13 17:06 UTC by srisatyavinay

2022-04-15 08:37 UTC, vjspranav requested changes

2022-04-15 08:37 UTC, vjspranav commented on experiment/simulation/js/flipflop.js
> +	for (let i = 0; i < x.length; i++) {
As thee is no assignment happening here
you could've probably used a forEach ? until unless it caused some problems.

2022-04-15 08:37 UTC, vjspranav commented on experiment/simulation/js/flipflop.js
> +		if (selectedTab === currentTab.NEG && m === 1) {
Maybe, this if else section can be done as a dictionary?, something like
```
const imagePaths = 
{
  currentTab.NEG: {
    1: "path"
    2: "path"
}
...
```

then you can do 
```
document.getElementById("graph-image").src = imagePaths[selectedTab][m]
```

this should look better

2022-04-15 12:13 UTC, srisatyavinay commented
As of now the images are not correct. We will change the image src soon.

2022-04-16 00:17 UTC, srisatyavinay commented on experiment/simulation/js/flipflop.js
> +	for (let i = 0; i < x.length; i++) {
We want to leave them as for loop itself sir because changing everything will take a lot of time

2022-04-16 00:17 UTC, srisatyavinay commented on experiment/simulation/js/flipflop.js
> +		if (selectedTab === currentTab.NEG && m === 1) {
Now changed it into a javascript object

2022-04-16 00:59 UTC, srisatyavinay commented on experiment/simulation/js/flipflop.js
> +		if (selectedTab === currentTab.NEG && m === 1) {
Changed that into javascript objects

2023-08-10 08:13 UTC, merged